### ISSUE TITLE
cl_ejectbrass 0 can cause crashes playing heavy

### ISSUE THREAD

**Issue by joebonrichie** [RhapsodySL/perfconfig#17]
I've had this issue for a longtime
http://teamfortress.tv/thread/22134/hl2-exe-crashing-when-playing-heavy

setting cl_ejectbrass 1 fixes this.

Option 1 - move cvar to experimental section in cfg and a comment to enable if experiencing crashes playing heavy
Option 2 - do a timedemo and see whether enabling it by default causes any real fps loss, if not enable the cvar by default

**Comment by RhapsodySL** [comment]
Fixed by https://github.com/RhapsodySL/perfconfig/commit/c3e2e1891c7ac49e9cdfa473b5687626cc2dd8b8
