### ISSUE TITLE
Typo in Shadows section

### ISSUE THREAD

**Issue by anijatsu** [RhapsodySL/perfconfig#18]
Line 100 of the autoexec file:
*(...)* ;r_shadowrendertotexture 1;**r shadows 1**;cl_blobbyshadows 0; *(...)*
It should be "r_shadows".

**Comment by RhapsodySL** [comment]
Fixed in https://github.com/RhapsodySL/perfconfig/commit/630cddfc8e4696cbbbdf1d6d86b6b7a7ff7c3006
