### ISSUE TITLE
I have a problem with my custom crit sound with this config

### ISSUE THREAD

**Issue by hero5jungle** [RhapsodySL/perfconfig#21]
The crit sounds like a very high static noise with this config

**Comment by RhapsodySL** [comment]
Hiya, sorry I didn't get around to this, I've been pretty busy up until now.

As far as I can tell, my config probably wouldn't do this, but if you think it's my config, go to line 176 (https://github.com/RhapsodySL/perfconfig/blob/master/tf/cfg/autoexec.cfg#L176), and remove everything between that and line 192. After you save the config, put -autoconfig into your launch options to reset every changed convar back to default, and start up the game. Make sure to remove that launch option after you do!

Alternatively, you can just forgo putting in the launch option and just change your sound settings to what you want after you remove them from the config, but I'm not sure if this would undo the changes.

**Comment by RhapsodySL** [comment]
Closing due to lack of response.
