### ISSUE TITLE
Issue with updater .bat not finding wget.

### ISSUE THREAD

**Issue by augustonite** [RhapsodySL/perfconfig#24]
A simple fix to increase reliability, have the bat cd the folder that wget.exe is in, allowing the "wget ..." command to execute properly.

For example,
```batch
cd "C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\rhapsody"
::And the rest as normal
wget https://raw.githubusercontent.com/RhapsodySL/perfconfig/master/tf/cfg/autoexec.cfg -O "C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\cfg\autoexec.cfg" --no-check-certificate
exit

```

**Comment by RhapsodySL** [comment]
Should've gotten to this much earlier. I went ahead and did this, but it also required setting the current dir as a the working dir. Regardless, it's done.

While I did that, I also decided to add a check to see if the user is on a 32-bit or 64-bit OS and change the installation path accordingly. As a result of this, I've also created an updater-legacy.bat file that users should use if they have TF2 installed somewhere other than the default directory. All they need to do in that file is replace the path.
