### ISSUE TITLE
Hides UFOs in Invasion update

### ISSUE THREAD

**Issue by Decimation** [RhapsodySL/perfconfig#26]
UFOs in the newest update  (9/10) are not shown when using the config.

**Comment by RhapsodySL** [comment]
Not sure why, unfortunately. I'll look into it in a little bit.

**Comment by Decimation** [comment]
Thank you!

**Comment by Decimation** [comment]
Just figured it out! It's either r_3dsky 0 or r_occlusion 1.

**Comment by RhapsodySL** [comment]
Sorry I didn't get to this earlier. While this is a a visual that doesn't show, it fits within the purview of this config to not show it. You can make it appear again by toggling the above convars.
