### ISSUE TITLE
Water Reflection

### ISSUE THREAD

**Issue by TerminatorT800** [RhapsodySL/perfconfig#27]
Which commands are responsible for this?:
http://steamcommunity.com/sharedfiles/filedetails/?id=584371257

Wouldn't mind removing it myself
I've tried changing r_waterdrawreflection, but I was having issues later with crashes on multiplayer

**Comment by RhapsodySL** [comment]
I honestly have no idea. It hasn't happened to me in my testing.

**Comment by TerminatorT800** [comment]
So you don't get a copy of the surrounding area around the water drawn on the water?

**Comment by RhapsodySL** [comment]
Negative. Sorry.
