### ISSUE TITLE
"AMD Compatibility"?

### ISSUE THREAD

**Issue by kamild1996** [RhapsodySL/perfconfig#34]
The "experimental" section of the setup mentions "AMD compatibility". What kind of compatibility precisely? With their processors or with their GPUs?

**Comment by RhapsodySL** [comment]
In all honesty, I don't even remember what the option was referring to other than that there was either some convar that was supposedly for better AMD compatibility (on the CPU front, probably), or that one of the options could cause crashes on AMD CPUs. Regardless, it's not particularly relevant at this point and was only included for completeness.
